name:test artifacts
on: push
jobs:
  runs-on: linux
  
  steps:
    - name: gen Upload1

      uses: actions/checkout@v3

      run: echo hello1 > world1.txt

    - name: Upload1

      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt


    - name: gen Upload2

      uses: actions/checkout@v3

      run: echo hello2 > world2.txt

    - name: Upload2

      uses: actions/upload-artifact@v3
      with:
        name: my-artifact222
        path: world222.txt
